# Generated by Django 5.2.4 on 2025-08-16 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangkapanikan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ikan',
            name='jenis_ikan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_ikan', to='api.jenisikan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ikan',
            name='nama_ikan',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jenisikan',
            name='nama',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tangkapanikan',
            name='jenis_ikan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.jenisikan'),
        ),
    ]
