# Generated by Django 5.2.4 on 2025-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tangkapanikan_created_at_alter_ikan_jenis_ikan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangkapanikan',
            name='jumlah',
            field=models.IntegerField(default=0),
        ),
    ]
