# Generated by Django 5.2.4 on 2025-08-06 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_realisasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_ikan', models.CharField(max_length=100)),
                ('total_kuota', models.IntegerField()),
                ('kuota_terpakai', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pelabuhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_ikan', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('lokasi_tangkap', models.CharField(max_length=100)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ship')),
            ],
        ),
    ]
