# Generated by Django 5.2.4 on 2025-08-19 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tangkapanikan_jumlah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kapal',
            name='no_reg_bkp',
        ),
        migrations.AlterField(
            model_name='kapal',
            name='no_buku_kapal',
            field=models.CharField(default='DEFAULT_NOMOR', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tangkapanikan',
            name='kapal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='api.kapal', to_field='no_buku_kapal'),
        ),
    ]
