# Generated by Django 5.2.4 on 2025-08-19 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_kapal_no_reg_bkp_alter_kapal_no_buku_kapal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuotaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(help_text='Gunakan tanggal awal bulan, contoh: 2025-08-01')),
                ('kuota_total', models.FloatField(help_text='Total kuota global (kg/ton)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('tutup', 'Ditutup')], default='aktif', max_length=10)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('ditetapkan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuota_ditetapkan', to=settings.AUTH_USER_MODEL)),
                ('jenis_ikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuota_global', to='api.jenisikan')),
                ('wpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuota_global', to='api.wpp')),
            ],
            options={
                'ordering': ['-periode'],
                'unique_together': {('periode', 'jenis_ikan', 'wpp')},
            },
        ),
        migrations.CreateModel(
            name='KuotaKapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuota', models.FloatField(help_text='Kuota dialokasikan untuk kapal ini (kg/ton)')),
                ('kuota_terpakai', models.FloatField(default=0, help_text='Kuota yang sudah dipakai (kg/ton)')),
                ('kapal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alokasi_kuota', to='api.kapal')),
                ('kuota_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alokasi', to='api.kuotaglobal')),
            ],
            options={
                'unique_together': {('kuota_global', 'kapal')},
            },
        ),
        migrations.AddField(
            model_name='tangkapanikan',
            name='kuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penangkapan', to='api.kuotakapal'),
        ),
    ]
