# Generated by Django 5.2.4 on 2025-08-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kuotaglobal_kuotakapal_tangkapanikan_kuota'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kuotakapal',
            unique_together={('kapal',)},
        ),
        migrations.AlterField(
            model_name='kuotakapal',
            name='kuota',
            field=models.FloatField(help_text='Total kuota kapal (kg/ton)'),
        ),
        migrations.RemoveField(
            model_name='kuotakapal',
            name='kuota_global',
        ),
        migrations.DeleteModel(
            name='KuotaGlobal',
        ),
    ]
