# Generated by Django 5.2.4 on 2025-08-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ikan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tangkapan',
            old_name='lokasi_tangkap',
            new_name='lokasi',
        ),
    ]
