# Generated by Django 5.2.4 on 2025-08-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_kuotakapal_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tangkapanikan',
            name='jumlah',
        ),
    ]
