# Generated by Django 5.2.5 on 2025-08-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_tangkapanikan_jumlah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tangkapanikan',
            name='kuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penangkapan', to='api.kapal'),
        ),
        migrations.AddField(
            model_name='kapal',
            name='kuota',
            field=models.FloatField(default=0, help_text='Total kuota kapal (kg/ton)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kapal',
            name='kuota_terpakai',
            field=models.FloatField(default=0, help_text='Kuota yang sudah dipakai (kg/ton)'),
        ),
        migrations.DeleteModel(
            name='KuotaKapal',
        ),
    ]
