# Generated by Django 5.2.4 on 2025-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_lokasi_tangkap_tangkapan_lokasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPP',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
