# Generated by Django 5.2.5 on 2025-08-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tangkapanikan_kuota_kapal_kuota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kapal',
            name='kuota',
        ),
        migrations.RemoveField(
            model_name='kapal',
            name='kuota_terpakai',
        ),
        migrations.CreateModel(
            name='KuotaKapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuota', models.FloatField(help_text='Total kuota kapal (kg/ton)')),
                ('kuota_terpakai', models.FloatField(default=0, help_text='Kuota yang sudah dipakai (kg/ton)')),
                ('kapal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alokasi_kuota', to='api.kapal')),
            ],
            options={
                'unique_together': {('kapal',)},
            },
        ),
        migrations.AlterField(
            model_name='tangkapanikan',
            name='kuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penangkapan', to='api.kuotakapal'),
        ),
    ]
